const WALLET_ADDRESS_WITH_ENOUGH_OCEANS = 'wallet'
const WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS = 'wallet_address'

module.exports = {WALLET_ADDRESS_WITH_ENOUGH_OCEANS, WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS}