const { WALLET_ADDRESS_WITH_ENOUGH_OCEANS } = process.env
const { WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS } = process.env

module.exports = {
  WALLET_ADDRESS_WITH_ENOUGH_OCEANS,
  WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS
}
