{
  'extends': ['oceanprotocol', 'plugin:prettier/recommended'],
  'plugins': ['prettier'],
  rules:
    {
      'camelcase': 'off',
      'prettier/prettier': ['error', { 'endOfLine': 'auto' }]
    },
  'env': { 'es6': true, 'browser': true, 'jest': true, 'node': true }
}
